---
title: "Data Cleaning"
author: "Michelle Kurilla"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(ggplot2)
library(viridis)
library(rstanarm)
library(gt)
library(gtsummary)
library(DT)
```

# Read Initial CSI Index XLS File 

```{r}

# read excel file
# name csi_index to distinguish from justice_excel 

csi_index <- 
    read_excel("CSI_1953_2014.xls")

```

# Sort Mean and Median of CSI Index by Year

```{r}

mean_median_csi <- csi_index %>%
  select(caseId, CSI) %>%
  mutate(caseId = str_sub(caseId, 1, 4)) %>%
  rename(year = caseId) %>%
  group_by(year) %>%
  summarize(mean = mean(CSI), 
           median = median(CSI))

```

# Read Justice_Opinion CSV

```{r, message = FALSE, error = FALSE}

# Read justice_opinion_csv
# Set cols argument 
# the excel file has many rows
# though I mostly plan to work with cols like caseId
# I didn't want to lose any columns and loaded all of them 

justice_opinion_excel <- read_csv("SCDB_2020_01_justiceCentered_Citation_2.csv",
                                  col_types = cols(
  .default = col_double(),
  caseId = col_character(),
  docketId = col_character(),
  caseIssuesId = col_character(),
  voteId = col_character(),
  dateDecision = col_character(),
  usCite = col_character(),
  sctCite = col_character(),
  ledCite = col_character(),
  lexisCite = col_character(),
  chief = col_character(),
  caseName = col_character(),
  dateArgument = col_character(),
  dateRearg = col_character(),
  lawMinor = col_character(),
  justiceName = col_character()
))

```

# Sum Cases by Chief Justices 

```{r}

justice_cases_sum <-
  
# pipe in justice_opinion_excel tibble
  
justice_opinion_excel %>%
  
# select columns to work with 
  
select(caseId, majOpinWriter) %>%
  
# the columns repeat; use distinct() function 
  
distinct() %>%
  
# mutate caseId to only include first four digits
  
mutate(caseId = str_sub(caseId, 1, 4)) %>%
  
# drop na values
  
drop_na() %>%
  
# filter to only chief justices
  
filter(majOpinWriter %in% c(90, 99, 102, 111)) %>%
  
# group by chief justices and caseId
  
group_by(majOpinWriter, caseId) %>%
  
# tally the total number of cases
  
tally() %>%

# rename n to total cases assigned
  
rename(total_cases_assigned = n) %>%
  
# rename the four digit caseId code to year 
  
rename(year = caseId)

```

# Justice CSV (join CSI and Justice Opinion Excel)

```{r}

# create inner_join of two databases
# important to join data because then it only includes cases where
# the csi and caseId match 
# the justice_opinion_excel includes up to 2019 whereas the csi dataset
# only includes up to 2014

joined_csv <- inner_join(csi_index, justice_opinion_excel, by = "caseId")

```

# Case Sum by Justice (Sum Total)

```{r}

judge_cases_sum <-
  
  # pipe in justice_opinion_excel
  
  justice_opinion_excel %>%
  
  # select columns to work with 
  
  select(caseId, majOpinWriter, majOpinAssigner) %>%
  
  # only use distinct() rows
  
  distinct() %>%
  
  # mutate caseId to get rid of trailing ID numbers
  
  mutate(caseId = str_sub(caseId, 1, 4)) %>%
  
  # drop na values
  
  drop_na() %>%
  
  # filter so that the Chief Justice both assigned and wrote the opinion 
  
  filter(majOpinWriter %in% c(90, 99, 102, 111), 
         majOpinAssigner %in% c(90, 99, 102, 111)) %>%
  filter(majOpinAssigner == majOpinWriter) %>%
  
  # rename to actual justice names 
  
  mutate(writer_name = case_when(majOpinWriter == 90 ~ "Warren", 
            majOpinWriter == 99 ~ "Burger", 
            majOpinWriter == 102 ~ "Rehnquist", 
            majOpinWriter == 111 ~ "Roberts")) %>% 
  mutate(assigner_name = case_when(majOpinAssigner == 90 ~ "Warren", 
            majOpinAssigner == 99 ~ "Burger", 
            majOpinAssigner == 102 ~ "Rehnquist", 
            majOpinAssigner == 111 ~ "Roberts")) %>%
  
  # group_by names and caseId 
  
  group_by(writer_name, caseId) %>%
  
  # tally total cases
  
  tally() %>%
  
  # rename n to total cases written 
  
  rename(total_cases_written = n) %>%
  
  # rename mutated caseId to year it was written
  
  rename(year = caseId)

```

## Modeling (Make "Test" with Joined CSV)

```{r}

# named it joined_csv equal to distinguish it from my other joined_csv objects
# the joined_csv objects are later used in the stan_glms to model

joined_csv_equal <- 
  
  # pipe in joined csv
  
  joined_csv %>%
  
  # select columns to work with 
  
  select(CSI, caseId, majOpinWriter, majOpinAssigner) %>%
  
  # filter to distinct data
  
  distinct() %>%
  
  # drop na values
  
  drop_na() %>%
  
  # mutate to create test column 
  
  mutate(test = if_else(majOpinAssigner == majOpinWriter, 1, 0)) 


```

## Modeling (Make Stan GLMs)

```{r}

# create stan_glm
# use joined_csv_equal created above for this stan_glm
# set refresh = 0 for stan_glm to run 
# initially tried too many variables at once, so I settled on using test
# modeling the difference between CSI scores when the Chief Justice assigns 
# and writes the case versus when they do not

fit_obj_test <- stan_glm(CSI ~ test,
                         data = joined_csv_equal, 
                         refresh = 0)

# print model with 4 digits to see the impact 

```

## GT Table by hnad 

```{r}

# pull numbers from stan_glm above

regression_1 <- tibble(coefficient = 0.8419, 
                       intercept = 2.6716)

# use gt() function to create gt table

gt(regression_1)

```

# writer name & csi 

```{r}

joined_csv_judge <-
  
  # pipe in justice_opinion_excel
  
joined_csv %>%
  
  # select columns to work with 
  
  select(caseId, majOpinWriter, majOpinAssigner, CSI) %>%
  
  # only use distinct() rows
  
  distinct() %>%
  
  # drop na values
  
  drop_na() %>%
  
  # filter so that the Chief Justice both assigned and wrote the opinion 
  
  filter(majOpinWriter %in% c(90, 99, 102, 111), 
         majOpinAssigner %in% c(90, 99, 102, 111)) %>%
  filter(majOpinAssigner == majOpinWriter) %>%
  
  # rename to actual justice names 
  
  mutate(writer_name = case_when(majOpinWriter == 90 ~ "Warren", 
            majOpinWriter == 99 ~ "Burger", 
            majOpinWriter == 102 ~ "Rehnquist", 
            majOpinWriter == 111 ~ "Roberts")) %>% 
  mutate(assigner_name = case_when(majOpinAssigner == 90 ~ "Warren", 
            majOpinAssigner == 99 ~ "Burger", 
            majOpinAssigner == 102 ~ "Rehnquist", 
            majOpinAssigner == 111 ~ "Roberts")) %>%
  
  # deselect majOpinWriter and majOpinAssigner because the numbers are hard to 
  # model & assigner_name is the same as writer_name

  select(-majOpinWriter, -majOpinAssigner, -assigner_name)

View(joined_csv_judge)

```

# create fit_obj_judge

```{r}

# create output of CSI and use writer_name as coefficient 
# use created joined_csv_judge
# set refresh = 0 for stan_glm to run 
# modeling the difference between CSI scores when different Chief Justice assign 
# and write cases
# the data is already filtered to instances where the Chief Justices are writing
# and assigning the cases 

fit_obj_judge <- stan_glm(CSI ~ writer_name,
                         data = joined_csv_judge, 
                         refresh = 0)

# print model with four digits to see the changes 

```

# Regression 2

```{r}

# manually set data for gt tibble

regression_2 <- tibble(Burger = 3.3632, 
                       Rehnquist = 3.3000, 
                       Roberts = 3.3103, 
                       Warren = 3.6965)

# create gt with gt() function 

gt(regression_2)

```
